<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>eskip</string>
    <key>scopeName</key>
    <string>source.eskip</string>
    <key>uuid</key>
    <string>d1e0f704-3337-5b48-aa59-e11e3f419802</string>
    <key>fileTypes</key>
    <array>
      <string>eskip</string>
    </array>
    <key>repository</key>
    <dict>
      <key>comment-single_line</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.single_line.eskip</string>
            <key>match</key>
            <string>\/\/.*$</string>
          </dict>
        </array>
      </dict>
      <key>constant-language-shunt</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.language.shunt.eskip</string>
            <key>match</key>
            <string>&lt;shunt&gt;</string>
          </dict>
        </array>
      </dict>
      <key>constant-language-loopback</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.language.loopback.eskip</string>
            <key>match</key>
            <string>&lt;loopback&gt;</string>
          </dict>
        </array>
      </dict>
      <key>constant-language-match_any</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.language.match_any.eskip</string>
            <key>match</key>
            <string>\*</string>
          </dict>
        </array>
      </dict>
      <key>keyword-operator-arrow</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.operator.arrow.eskip</string>
            <key>match</key>
            <string>-&gt;</string>
          </dict>
        </array>
      </dict>
      <key>keyword-operator-and</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.operator.and.eskip</string>
            <key>match</key>
            <string>&amp;&amp;</string>
          </dict>
        </array>
      </dict>
      <key>punctuation-comma</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>punctuation.comma.eskip</string>
            <key>match</key>
            <string>,</string>
          </dict>
        </array>
      </dict>
      <key>punctuation-colon</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>punctuation.colon.eskip</string>
            <key>match</key>
            <string>:</string>
          </dict>
        </array>
      </dict>
      <key>punctuation-semicolon</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>punctuation.semicolon.eskip</string>
            <key>match</key>
            <string>;</string>
          </dict>
        </array>
      </dict>
      <key>punctuation-quote-double</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>punctuation.quote.double.eskip</string>
            <key>match</key>
            <string>"</string>
          </dict>
        </array>
      </dict>
      <key>brace-round-open</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>brace.round.open.eskip</string>
            <key>match</key>
            <string>\(</string>
          </dict>
        </array>
      </dict>
      <key>brace-round-close</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>brace.round.close.eskip</string>
            <key>match</key>
            <string>\)</string>
          </dict>
        </array>
      </dict>
      <key>constant-numeric-float</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.numeric.float.eskip</string>
            <key>match</key>
            <string>\d+|\d+\.\d+</string>
          </dict>
        </array>
      </dict>
      <key>string-quoted-double</key>
      <dict>
        <key>begin</key>
        <string>(")</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.quote.double.eskip</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(")</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.quote.double.eskip</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.eskip</string>
      </dict>
      <key>entity-name-route</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>entity.name.route.eskip</string>
            <key>match</key>
            <string>[a-zA-Z0-9_]+</string>
          </dict>
        </array>
      </dict>
      <key>basic</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-quoted-double</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constant-language-shunt</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constant-language-loopback</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constant-language-match_any</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keyword-operator-arrow</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keyword-operator-and</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constant-numeric-float</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment-single_line</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>patterns</key>
    <array>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#basic</string>
          </dict>
        </array>
        <key>begin</key>
        <string>([a-zA-Z0-9_]+)(\s*)(:)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.route.eskip</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.colon.eskip</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(;)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.semicolon.eskip</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.route.eskip</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#basic</string>
      </dict>
    </array>
  </dict>
</plist>
